astropy/astropy-tools

suggest_backports.py

This is an adjustment to the suggest_backports script to resolve an error both @astrofrog and I were encountering.  I've included the traceback at the end of what we currently both see in master.  
It looks to me like what's changed is that the ``pkg_resources.parse_version`` function used to return a rather strangely-formatted tuple to allow comparison to work, but now (where "now" is defined as "yesterday on @astrofrog and my machines") it's a custom object with method-level comparison implementations.  But that makes the stuff in `get_last_tag` fail because it's no longer iterable.  So this PR just changes that to instead use direct string comparison to determine if a tag and a branch are the same.  Look right to you, @embray ?
```
Traceback (most recent call last):
File …
```

Make suggest_backports use string version comparison

---

astropy_grep_affiliated

Replaces astropy/astropy#3629.
In trying to answer some questions about the usage of the configuration package among affiliated packages, I found this tool to be pretty useful.
```
./astropy_grep_affiliated ConfigItem
```
opens the following URL:
https://github.com/search?q=repo%3Aastropy%2Fspecutils+repo%3Aastropy%2Fastroquery+repo%3Aastropy%2Fphotutils+repo%3Aeteq%2Fastropysics+repo%3Aejeschke%2Fg+repo%3AastroML%2Fast+repo%3Aweaverba137%2Fpydl+repo%3Aaplpy%2Faplpy+repo%3Agammapy%2Fgammapy+repo%3Aastropy%2Fccdproc+repo%3Asncosmo%2Fsnc+repo%3Aspacetelescope%2Fim+ConfigItem&type=Code
Thought it might be useful...  wasn't exactly sure where to put it, so put it under a new `devtools` directory.  I could also just share it as a gist if it doesn't belong in the repo.

Add tool to search affiliated packages

---

.gitignore
LICENSE.rst
astropy_grep_affiliated.py
gh_issuereport.py
issue2pr.py
setup.py
suggest_backports.py

This is mostly just for convenience--this doesn't mean we would package or distribute astropy-tools.
But this way I can just clone astropy-tools and run:
```
$ ./setup.py develop
```
and get links to the latest versions of the tools in this repository installed into whatever environment I want to have them in.  Use of this is of course totally optional.
Also added a license.

Add a setup.py

---

issue2pr.py

This builds on #3, but also could be separated out.  It brings two enhancements to the issue2pr.py script:
1) It now uses the requests module to interact with the GH API.  This makes the code almost trivial.  It's not a big deal to have requests installed, and #3 also requires it.  
2) This change in turn makes it trivial to fix the script to work on Python 3, since requests works on Python 3.  Now I don't have to keep running 
```
$ python2.7 `which issue2pr.py`
```
just to use this script ;)

Issue2pr requests

---

issue2pr.py

The two arguments where removed from the function a few days ago, but the arguments are still in the docstring.
@embray

Remove username and password from doctring in issue_to_pr

---

clean_parse_tables.py

This adds the ``clean_parse_tables.py`` script from astropy/astropy#4003 to this repo.  Will issue a companion PR in astropy/astropy shortly that removes it from there.

move clean_parse_tables.py from astropy to astropy-tools

---

changelog/1.get_merged_prs.py
changelog/2.find_pr_branches.py
changelog/3.find_pr_changelog_section.py
changelog/4.check_consistency.py
changelog/README.md
changelog/common.py
common.py
issue2pr.py
suggest_backports.py

This is still a work in progress, but the idea is to have a script that can check that milestones in PRs match the changelog and also match which maintenance branch the PR was backported to. At the moment, this just checks that milestones match the changelog section, and there's still some missing logic. I'm just putting this up here to make sure no one else tries to duplicate this effort :)
Example output so far:
```
v1.1.1: 1 out of 5 pull requests had issues:
Milestone for pull request #4452 is v1.0.8 but is in the changelog section for v1.1.1
v1.1.2: 7 out of 16 pull requests had issues:
Milestone for pull request #4489 is v1.0.9 but is in the changelog section for v1.1.2
Milestone for pull request #4514 is v1.0.9 but is in the changelog section for v1.1.2
Milestone for pull request …
```

Scripts to check changelog consistency

---

clean_parse_tables.py

There are utf characters in some of the newly generated parsing tables, so the coding was put on the first line making the licence to start on the second.

Allowing Licence can start at the second line

---

add_to_changelog.py

This is a straightforward tool that generates a new section for the astropy changelog.  Just use it as it says in the header docstring.
(Note that this will be used in a forethecoming modification to the astropy release isntructions)

added add_to_changelog.py

---

changelog/1.get_merged_prs.py

@eteq - this solves the issues I was seeing, and is cleaner anyway because it allows us to use the ``since`` option in ``get_issues`` to only iterate over issues that have changed since a certain date.

Refactor changelog script to iterate through issues

---

pr_consistency/3.find_pr_changelog_section.py

The current script has the bug that the BLOCK_PATTERN matches the whole set content for a given version number (due to ``[`` and ``]`` falls into the match of ``.+``) rather than just the brackets with the PR/issue number at the end of each entry.
This PR also adds the option that the numbers are listed in parenthesis rather than bracket (see e.g. astroquery).

Fix regex in changelog script

---

pr_consistency/3.find_pr_changelog_section.py

e.g. astroquery has ``CHANGES`` and the script obviously didn't like it.

Add option to specify non CHANGES.rst named changelog

---

.gitignore
pr_consistency/1.get_merged_prs.py
pr_consistency/4.check_consistency.py

This fixes the first script for the case when no json file is present and one has to start from scratch. This closes #27.
Also adding a close date for 1.2.x and the generated json files to gitignore.

Fixing scripts when starting with empty json

---

unify_section_headings.py

Ref #328 - set a standard ordering of section header chars throughout the docs.
This is the script used to generate the changes in https://github.com/astropy/astropy/pull/3216 for https://github.com/astropy/astropy/issues/328
Based on original gist by @taldcroft: https://gist.github.com/taldcroft/3208992

Unify section headings script

---

update-affiliated/update_astropy_helpers.py

* We shouldn't update ``package-template`` this way as cookiecutter totally changed the structure of the package.
* It's so easy to forgot to update the version string in the script, less mysterious if it's a mandatory command line argument.

Minor updates to the helpers updating script

---

update-affiliated/update_astropy_helpers.py

While we will remove ez_setup at some point in the near future releases, it would be good to have the latest upgrade propagated to the affiliates before we do that.

HELPERS_UPDATE: Updating ez_setup.py along with the helpers

---

pr_consistency/2.find_pr_branches.py

This is a minor convenience in find_pr_branches that lets you turn off fetching if there's a reason to do so.  I can't recall exactly when this came up, but I think it might have been when testing either against some temporary fix branch or when internet was being flaky

Let no fetching happen in 2.find_pr_branches.py

---

update-affiliated/update_astropy_helpers.py

There is no need to fetch everything from `upstream`, right?

Fetch upstream master explicitly

---

update-affiliated/helpers_2.py

Five packages added that use the astropy affiliated template and could use automated PRs to update astropy-helpers.  All these packages should by python 2 and 3 compatible for now - so adding them to the helpers_2.py file.  May change this in the future, but then will create pull requests as needed.

Adding in packages I manage that use the astropy affiliated template

---

astropy_usage.py

The script is full of hacks to circumvent the github API rate limit and the search result limitations to 1000 entries.
Surely, this script should go into a subdirectory, but I wasn't sure whether "demographics" is the best place or starting a new one.
The results from running the script the week prior 18/04/18 are stored in a pickled dictionary, here: https://drive.google.com/file/d/1g1I4UTFaN5zQkYl0aipEcjFdbdvNDria/view?usp=sharing

Adding Astropy usage script

---

ci_helpers_usage.py

The question of ci-helpers usage came up now several times, so adding this snippet may be useful in the future, too.
Obviously this uses the over simplified assumption that if the repo name is mentioned in the travis configuration then it's used.

Add script to check ci-helpers usage

---

documents/affiliated_package_review_guidelines.md
documents/affiliated_package_review_process.md

Just some minor improvements - we send a link to the guidelines to reviewers, so just want to make sure they make sense to them.

Improve review guidelines for affiliated packages

---

update-packages/helpers_2.py

As changes should be done there differently on the cookiecutter branch rather than in the rendered version of master

Remove the package-template from the auto update list

---

update-packages/helpers_2.py

Astrospec was meant as an alternative implementation for specutils at a time when that package was langushing. There is still stuff in astrospec that I plan to port to specutils at some point, but it's only a few functions and I don't maintain astrospec as a real "package" any longer.

Remove hamogu/astrospec

---

update-packages/helpers_2.py

This PR removes imexam from the auto-pr list

imexam no longer uses astropy_helpers

---

pr_consistency/4.check_consistency.py

To work around slight labeling inconsistencies between repositories

Adding more variants for 'affects-dev'

---

documents/affiliated_package_review_guidelines.md

Just a small wording change to the affiliated package guidelines

Clarify exact date for requiring Python 3 support

---

pr_consistency/3.find_pr_changelog_section.py

When doing a release with bugfix branches it makes more sense to use the local changelog file (e.g. on the bugfix branch) to check for consistency rather than the out-of-sync version on the remote.

Make script to work with local changelog file

---

documents/affiliated_package_review_process.md

In astropy/astropy.github.com#315 I realized our default wording at the end of the review process is a bit odd for an accepted-with-orange review, because we merge the PR but still ask for feedback in the thread.  So I added a bit here that basically just says "make a new PR to update this to trigger more discussion".  I think that's more realistic to keep up with - do you agree, @astrofrog?

tweak wording at end of review

---

pr_consistency/1.get_merged_prs_graphql.py

This fetches all PRs in less than a minute! (as opposed to many hours)
Keeping the old script for now until I'm convinced the new results are exactly the same. For a few PRs (e.g. #1041) there seems to be an issue where the merge commit is not set in the graphql response, I've contacted GitHub about this. But otherwise the output seems to match.
Fixes https://github.com/astropy/astropy-procedures/issues/39

Added GraphQL version of get_merged_prs.py

---

pr_consistency/1.get_merged_prs.py
pr_consistency/4.check_consistency.py

This fixes two separate things:
* Fetch more than 10 labels per pull request otherwise we miss changelog related labels in some cases where there are lots of labels on a pull request
* Recognize the skip-changelog-checks as meaning the same as no-changelog-entry-needed

Fixes related to labels

---

.github/workflows/update_org_members.yml
add_contributors_to_org.py
coordinated_package_policies.json

The intent of this is to semi-automate adding people who have had PRs merged in coordinated packages (or astropy core) added to the astropy organization so that coordinated package maintainers can assign them to issues, etc.
To do before merging:

Add script for adding contributors

---

.github/workflows/update_org_members.yml

This pull request is the last step in implementing a bot that will send invitations to contributors to coordinate packages that have had at least one pull request merged. 
The actual code is at https://github.com/astropy/astropy-tools/blob/main/add_contributors_to_org.py
A recent run of this as a github action is here: https://github.com/astropy/astropy-tools/runs/7235474185?check_suite_focus=true
This closes #170 which tracks outstanding to-dos after the initial draft of the bot code.
- Periodically (currently daily) check pull requests merged in an Astropy coordinated package (see list [here](https://github.com/astropy/astropy-tools/blob/main/.github/workflows/update_org_members.yml#L30)) for PR authors who are not in the Astropy GitHub organization.
- If the person is not in the …

Automatically invite contributors to coordinated packages to Astropy GitHub org

---

.github/workflows/pr_consistency.yml
common.py
pr_consistency/2.find_pr_branches.py
pr_consistency/4.check_consistency.py

Just some small updates when working on 4.0.6

Stop checking consistency of pre-4.0 releases, close 4.2.x branch and add a manual backport

---

next_pr_number.py

Currently the next_pr_number script uses a somewhat brittle `sys.argv` approach.  This PR changes it to use argparse, which I find has more helpful error messages and hints on usage.

switch next_pr_number.py to use argparse

---

pr_consistency/1.get_merged_prs.py
pr_consistency/3.find_pr_changelog_section.py

Much smaller scope than #158 and should be uncontroversial.
The other occurrences happen in files that I want to get rid of anyway.
Close #157

MNT: Replace master with main in pr_consistency

---

.github/workflows/update_org_members.yml.disabled

As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)

MNT: Use hash for Action workflow versions and update if needed
