astropy/astropy-tools

suggest_backports.py
This can be used to check for backports from e.g. v1.0.7 PRs into v1.1.x
cc @eteq @embray
=> Allow milestone to be specified in suggest_backports

changelog/1.get_merged_prs.py, changelog/2.find_pr_branches.py, changelog/4.check_consistency.py, changelog/README.md
This is a set of updates to @astrofrog's scripts based on the 1.3rc1 review process.
Probably should have separated this out into a few separate commits/PR's, but... eh ...
=> Omnibus updates for 1.3rc1 process

update-affiliated/update_astropy_helpers.py
@Cadair asked to include sunpy in the update list.
=> Adding sunpy to the list of packages requiring helpers update

update-affiliated/update_astropy_helpers.py
More packages are added to the list.
=> Adding packages to the list for autoupdate helpers

pr_consistency/1.get_merged_prs.py, pr_consistency/2.find_pr_branches.py, pr_consistency/3.find_pr_changelog_section.py, pr_consistency/4.check_consistency.py
Because these scripts are really great and it's a waste not to use them for at least the helpers.
=> Make PR scripts run with other repos

next_pr_number.py
Taking the fun out of it 😆 
```
$ python next_pr_number.py 
Next PR number: 6104
```
cc @pllim @bsipocz
=> Add a script to find the next PR number for the changelog

update-affiliated/update_astropy_helpers.py
Motivated by @mwcraig's comment here https://github.com/astropy/ccdproc/pull/441#issuecomment-267859944, it may be useful to list the person running the script as a recipient for issues.
=> Mentioning script running person for complaints

.gitignore, common.py, pr_consistency/2.find_pr_branches.py, pr_consistency/4.check_consistency.py
This is a partial fix for #41. Most part of 4.check_consistency.py need to updated to have custom branch closure dates, etc.
=> Branches in custom repos

pr_consistency/4.check_consistency.py
Maybe a bit premature, but I'm fairly certain that we won't do any more releases...
=> Closing branches of 1.0.x and 1.3.x with releases 1.0.13 and 1.3.3

pr_consistency/3.find_pr_changelog_section.py
Basically same hack as for the bot.
=> Release scripts to recognize the new changelog format

update-affiliated/update_astropy_helpers.py
No point updating the helpers in wcsaxes.
=> Removing wcsaxes from package list

update-affiliated/update_astropy_helpers.py
I should have found this sooner...
=> Add some STScI repos for auto helpers update

update-affiliated/update_astropy_helpers.py
To address https://github.com/astropy/pyregion/pull/122#issuecomment-336638834 
and moving the message to the top, reformatted for easier readability.
=> HELPERS_UPDATE: Adding link for changelog for helpers update

pr_consistency/4.check_consistency.py, pr_consistency/pr_checks.sh
Adding more manual merges, and simple script to run all python scripts...
=> PR_CONSISTENCY: Adding more manual merges

pr_consistency/pr_checks.sh
Fixing typo added by c0e7060a95e877564979a0d860985c583a044498
=> use the shell variables

pr_consistency/pr_checks.sh
Hopefully this is enough of a fix for #69 (to prevent it for the future, not to fix the current discrepancies).
=> PR_CONSISTENCY: Only run the next script if the previous one was successful

update-affiliated/common.py, update-affiliated/update_astropy_helpers.py
So my life becomes easier to work on borrowed computers...
=> Using either the stored credentials or prompt for them

visualizations_demographics/astropy_status_plots.py
A very minor fix to make one of the visualization/demographics tools work again
=> fix missing encode for py3 compatibility

next_pr_number.py
Why have deps when you can do it in less lines with just the stdlib
=> Change next_pr_number to not use github

visualizations_demographics/cites_and_mentions.py
This is copied from https://github.com/keflavich/astropy-graphs/, which was an old fork of the earliest version of this repo.  I'll add some examples to this PR.
=> Add tool to make citation & mention history plots

update-packages/helpers_3.py
Wow, I just found out about this. Neat!
=> Add PlasmaPy to helpers_3.py

update-packages/helpers_2.py, update-packages/helpers_3.py
This is a follow up of ejeschke/ginga#711
=> Move Ginga from PY2 to PY3 updates

update-packages/helpers_2.py, update-packages/helpers_3.py
Great to get the automated pull requests on my packages.  Missing two newer packages I maintain, so adding them with this pull request.
=> Two more packages for cool automated updates

utils.py
Have you ever stayed up late thinking about a problem and asked yourselves, "What would Erik do?" If you say "no", you are most certainly in denial. Deny yourselves no more! With one simple function call, it would answer this burning question so you can sleep well thereafter.
But wait, there's more! Errr... No, there's no more. This is it.
*Disclaimer: Only answer what Erik does in a very specific situation. Side effects might include restless legs and desire to gamble.*
=> What Would Erik Do

common.py, pr_consistency/4.check_consistency.py
This should be non controversial.
=> Adding 3.2.x branch, and close 3.1.x

update-packages/helpers_3.py
Note that this package is not yet affiliated, but I would like to get
automatic updates for it!
=> Add mhvk/scintillometry to the list of auto-PR packages

update-packages/helpers_2.py
I'm planning to remove astropy-helpers from naima. Thanks for the automated PRs up to now!
=> remove zblz/naima from helpers

pr_consistency/4.check_consistency.py
Well, this wasn't too bad.
close #144
=> Recognise the RC release changelog section as normal version without RC

update-packages/helpers_3.py
spacetelescope/synphot_refactor#229
spacetelescope/stsynphot_refactor#95
=> synphot and stsynphot no longer use astropy-helpers

update-packages/README.md
=> DOC: No more astropy-helpers updates

common.py, pr_consistency/1.get_merged_prs.py, pr_consistency/2.find_pr_branches.py, pr_consistency/3.find_pr_changelog_section.py, pr_consistency/4.check_consistency.py
(I also ran pyupgrade since the code is nicer with fstrings, I can move this to another PR if you prefer, or have a look at the second commit)
ping @eteq @bsipocz 
Fix  #159.
=> Fix pr_consistency to detect backport PRs from Meeseeks

pr_consistency/README.md
As I am removing the instructions in the astropy docs (https://github.com/astropy/astropy/pull/12755) just making sure the instructions here are up to date
=> Updated instructions for PR consistency checking

visualizations_demographics/astropy_status_plots.py
just what it says on the tin..
=> some minor updates to clean up the status plots
